<?php

$header = <<<'EOF'
This file is part of PHP-Compiler, a PHP CFG Compiler for PHP code

@copyright 2015 Anthony Ferrara. All rights reserved
@license MIT See LICENSE at the root of the project for more info
EOF;

$finder = PhpCsFixer\Finder::create()
	->name('.php_cs')
	->exclude('vendor')
	->exclude('.git')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
	->setIndent('    ')
	->setLineEnding("\n")
    ->setRules([
    	'header_comment' => [
    		'comment_type' => 'PHPDoc',
    		'header' => $header,
    	],
		'align_multiline_comment' => true,
		'array_indentation' => true,
		'array_syntax' => ['syntax' => 'short'],
		'binary_operator_spaces' => true,
		'blank_line_after_namespace' => true,
		'blank_line_after_opening_tag' => true,
		'blank_line_before_return' => true,
		'blank_line_before_statement' => true,
		'braces' => true,
		'cast_spaces' => true,
		'class_attributes_separation' => true,
		'class_definition' => true,
		'compact_nullable_typehint' => true,
		'concat_space' => true,
		'declare_strict_types' => true,
		'elseif' => true,
		'encoding' => true,
		'escape_implicit_backslashes' => true,
		'explicit_indirect_variable' => true,
		'explicit_string_variable' => true,
		'final_internal_class' => true,
		'fully_qualified_strict_types' => true,
		'full_opening_tag' => true,
		'function_declaration' => true,
		'function_typehint_space' => true,
		'hash_to_slash_comment' => true,
		'implode_call' => true,
		'include' => true,
		'increment_style' => true,
		'indentation_type' => true,
		'is_null' => true,
		'line_ending' => true,
		'linebreak_after_opening_tag' => true,
		'list_syntax' => ['syntax' => 'short'],
		'logical_operators' => true,
		'lowercase_cast' => true,
		'lowercase_constants' => true,
		'lowercase_keywords' => true,
		'lowercase_static_reference' => true,
		'magic_constant_casing' => true,
		'magic_method_casing' => true,
		'method_argument_space' => true,
		'method_chaining_indentation' => true,
		'modernize_types_casting' => true,
		'multiline_comment_opening_closing' => true,
		'multiline_whitespace_before_semicolons' => true,
		'native_constant_invocation' => true,
		'native_function_casing' => true,
		'new_with_braces' => true,
		'no_alternative_syntax' => true,
		'no_binary_string' => true,
		'no_blank_lines_after_class_opening' => true,
		'no_blank_lines_after_phpdoc' => true,
		'no_blank_lines_before_namespace' => true,
		'no_break_comment' => true,
		'no_closing_tag' => true,
		'no_empty_comment' => true,
		'no_empty_phpdoc' => true,
		'no_empty_statement' => true,
		'no_extra_blank_lines' => true,
		'no_leading_import_slash' => true,
		'no_leading_namespace_whitespace' => true,
		'no_mixed_echo_print' => true,
		'no_multiline_whitespace_around_double_arrow' => true,
		'no_multiline_whitespace_before_semicolons' => true,
		'no_short_bool_cast' => true,
		'no_short_echo_tag' => true,
		'no_singleline_whitespace_before_semicolons' => true,
		'no_spaces_around_offset' => true,
		'no_spaces_inside_parenthesis' => true,
		'no_superfluous_elseif' => true,
		'no_superfluous_phpdoc_tags' => true,
		'no_trailing_comma_in_list_call' => true,
		'no_trailing_comma_in_singleline_array' => true,
		'no_trailing_whitespace' => true,
		'no_trailing_whitespace_in_comment' => true,
		'no_unneeded_control_parentheses' => true,
		'no_unneeded_curly_braces' => true,
		'no_unneeded_final_method' => true,
		'no_unreachable_default_argument_value' => true,
		'no_unset_on_property' => true,
		'no_unused_imports' => true,
		'no_useless_else' => true,
		'no_useless_return' => true,
		'no_whitespace_before_comma_in_array' => true,
		'no_whitespace_in_blank_line' => true,
		'non_printable_character' => true,
		'normalize_index_brace' => true,
		'not_operator_with_successor_space' => true,
		'object_operator_without_whitespace' => true,
		'ordered_class_elements' => true,
		'ordered_imports' => true,
		'php_unit_construct' => true,
		'phpdoc_add_missing_param_annotation' => true,
		'phpdoc_align' => true,
		'phpdoc_indent' => true,
		'phpdoc_inline_tag' => true,
		'phpdoc_no_access' => true,
		'phpdoc_no_package' => true,
		'phpdoc_order' => true,
		'phpdoc_return_self_reference' => true,
		'phpdoc_scalar' => true,
		'phpdoc_separation' => true,
		'phpdoc_single_line_var_spacing' => true,
		'phpdoc_to_return_type' => true,
		'phpdoc_trim' => true,
		'phpdoc_types' => true,
		'return_assignment' => true,
		'return_type_declaration' => true,
		'self_accessor' => true,
		'semicolon_after_instruction' => true,
		'set_type_to_cast' => true,
		'short_scalar_cast' => true,
		'simplified_null_return' => true,
		'single_blank_line_at_eof' => true,
		'single_class_element_per_statement' => true,
		'single_import_per_statement' => true,
		'single_line_after_imports' => true,
		'single_quote' => true,
		'space_after_semicolon' => true,
		'standardize_increment' => true,
		'standardize_not_equals' => true,
		'static_lambda' => true,
		'strict_comparison' => true,
		'strict_param' => true,
		'string_line_ending' => true,
		'switch_case_semicolon_to_colon' => true,
		'switch_case_space' => true,
		'ternary_operator_spaces' => true,
		'ternary_to_null_coalescing' => true,
		'trailing_comma_in_multiline_array' => true,
		'trim_array_spaces' => true,
		'unary_operator_spaces' => true,
		'visibility_required' => true,
		'void_return' => true,
		'whitespace_after_comma_in_array' => true,
    ])
    ->setFinder($finder);
